-- MySQL Script generated by MySQL Workbench
-- Tue Nov 10 11:06:30 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AlquilerCoches
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `AlquilerCoches` ;

-- -----------------------------------------------------
-- Schema AlquilerCoches
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AlquilerCoches` DEFAULT CHARACTER SET utf8 ;
USE `AlquilerCoches` ;

-- -----------------------------------------------------
-- Table `AlquilerCoches`.`Fichero cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlquilerCoches`.`Fichero_cliente` (
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `id_cliente_UNIQUE` (`id_cliente` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlquilerCoches`.`Fichero coche`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlquilerCoches`.`Fichero_coche` (
  `matricula` INT NOT NULL AUTO_INCREMENT,
  `id_modelo` INT NOT NULL,
  `id_franquicia` INT NOT NULL,
  `estado_coche` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`matricula`, `id_modelo`, `id_franquicia`),
  UNIQUE INDEX `id_UNIQUE` (`matricula` ASC),
  INDEX `fk_Fichero_coche_Fichero_modelo_idx` (`id_modelo` ASC),
  INDEX `fk_Fichero_coche_Fichero_franquicia1_idx` (`id_franquicia` ASC),
  CONSTRAINT `fk_Fichero_coche_Fichero_modelo`
    FOREIGN KEY (`id_modelo`)
    REFERENCES `AlquilerCoches`.`Fichero_modelo` (`id_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fichero_coche_Fichero_franquicia1`
    FOREIGN KEY (`id_franquicia`)
    REFERENCES `AlquilerCoches`.`Fichero_franquicia` (`id_franquicia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlquilerCoches`.`Fichero extras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlquilerCoches`.`Fichero_extras` (
  `id_extra` INT NOT NULL AUTO_INCREMENT,
  `id_modelo` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `coste_adicional` DOUBLE NOT NULL,
  PRIMARY KEY (`id_extra`, `id_modelo`),
  UNIQUE INDEX `id_extra_UNIQUE` (`id_extra` ASC),
  INDEX `fk_Fichero_extras_Fichero_modelo1_idx` (`id_modelo` ASC),
  CONSTRAINT `fk_Fichero_extras_Fichero_modelo1`
    FOREIGN KEY (`id_modelo`)
    REFERENCES `AlquilerCoches`.`Fichero_modelo` (`id_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlquilerCoches`.`Fichero factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlquilerCoches`.`Fichero_factura` (
  `id_factura` INT NOT NULL AUTO_INCREMENT,
  `id_tarifa` INT NOT NULL,
  `importe` DOUBLE NOT NULL,
  `estado_factura` VARCHAR(45) NOT NULL,
  `tipo_pago` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_factura`, `id_tarifa`),
  UNIQUE INDEX `id_factura_UNIQUE` (`id_factura` ASC),
  INDEX `fk_Fichero_factura_Fichero_tarifa1_idx` (`id_tarifa` ASC),
  CONSTRAINT `fk_Fichero_factura_Fichero_tarifa1`
    FOREIGN KEY (`id_tarifa`)
    REFERENCES `AlquilerCoches`.`Fichero_tarifa` (`id_tarifa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlquilerCoches`.`Fichero franquicia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlquilerCoches`.`Fichero_franquicia` (
  `id_franquicia` INT NOT NULL AUTO_INCREMENT,
  `provincia` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_franquicia`),
  UNIQUE INDEX `id_franquicia_UNIQUE` (`id_franquicia` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlquilerCoches`.`Fichero modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlquilerCoches`.`Fichero modelo` (
  `id_modelo` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  `categoria_modelo` VARCHAR(45) NOT NULL,
  `num_puertas` INT NOT NULL,
  `manual/automatico` VARCHAR(45) NOT NULL,
  `tipo_techo` VARCHAR(45) NOT NULL,
  `combustible` VARCHAR(45) NOT NULL,
  `num_plazas` INT NOT NULL,
  `año` INT NOT NULL,
  PRIMARY KEY (`id_modelo`),
  UNIQUE INDEX `id_modelo_UNIQUE` (`id_modelo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlquilerCoches`.`Fichero reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlquilerCoches`.`Fichero_reserva` (
  `id_reserva` INT NOT NULL,
  `id_coche` INT NOT NULL,
  `id_modelo` INT NOT NULL,
  `id_franquicia` INT NOT NULL,
  `id_factura` INT NOT NULL,
  `estado_reserva` VARCHAR(45) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_reserva`, `id_coche`, `id_modelo`, `id_franquicia`, `id_factura`, `id_cliente`),
  INDEX `fk_Fichero_reserva_Fichero_coche1_idx` (`id_coche` ASC, `id_modelo` ASC, `id_franquicia` ASC),
  INDEX `fk_Fichero_reserva_Fichero_factura1_idx` (`id_factura` ASC),
  INDEX `fk_Fichero_reserva_Fichero_cliente1_idx` (`id_cliente` ASC),
  CONSTRAINT `fk_Fichero_reserva_Fichero_coche1`
    FOREIGN KEY (`id_coche` , `id_modelo` , `id_franquicia`)
    REFERENCES `AlquilerCoches`.`Fichero_coche` (`matricula` , `id_modelo` , `id_franquicia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fichero_reserva_Fichero_factura1`
    FOREIGN KEY (`id_factura`)
    REFERENCES `AlquilerCoches`.`Fichero_factura` (`id_factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fichero_reserva_Fichero_cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `AlquilerCoches`.`Fichero_cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlquilerCoches`.`Fichero tarifa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlquilerCoches`.`Fichero_tarifa` (
  `id_tarifa` INT NOT NULL AUTO_INCREMENT,
  `tipo_tarifa` VARCHAR(45) NOT NULL,
  `cambio_importe` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tarifa`),
  UNIQUE INDEX `id_tarifa_UNIQUE` (`id_tarifa` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlquilerCoches`.`reserva_tiene_extras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlquilerCoches`.`reserva_tiene_extras` (
  `Fichero_extras_id_extra` INT NOT NULL,
  `Fichero_extras_id_modelo` INT NOT NULL,
  `Fichero_factura_id_factura` INT NOT NULL,
  `Fichero_factura_id_tarifa` INT NOT NULL,
  PRIMARY KEY (`Fichero_extras_id_extra`, `Fichero_extras_id_modelo`, `Fichero_factura_id_factura`, `Fichero_factura_id_tarifa`),
  INDEX `fk_Fichero_extras_has_Fichero_factura_Fichero_factura1_idx` (`Fichero_factura_id_factura` ASC, `Fichero_factura_id_tarifa` ASC),
  INDEX `fk_Fichero_extras_has_Fichero_factura_Fichero_extras1_idx` (`Fichero_extras_id_extra` ASC, `Fichero_extras_id_modelo` ASC),
  CONSTRAINT `fk_Fichero_extras_has_Fichero factura_Fichero_extras1`
    FOREIGN KEY (`Fichero_extras_id_extra` , `Fichero_extras_id_modelo`)
    REFERENCES `AlquilerCoches`.`Fichero extras` (`id_extra` , `id_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fichero_extras_has_Fichero_factura_Fichero_factura1`
    FOREIGN KEY (`Fichero_factura_id_factura` , `Fichero_factura_id_tarifa`)
    REFERENCES `AlquilerCoches`.`Fichero_factura` (`id_factura` , `id_tarifa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;